default: &default
  adapter: postgresql
  username: ninomiya
  password: limelight
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: band_calender_development
  host: localhost

test:
  <<: *default
  database: band_calender_test
  host: localhost

production:
  <<: *default
  database: band_calender_production
  host:
